<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE4US72a\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE4US72a/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerE4US72a.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerE4US72a\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerE4US72a\App_KernelDevDebugContainer([
    'container.build_hash' => 'E4US72a',
    'container.build_id' => 'd8914ae2',
    'container.build_time' => 1637163779,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE4US72a');
