<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD7d4p8H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD7d4p8H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD7d4p8H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD7d4p8H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD7d4p8H\App_KernelDevDebugContainer([
    'container.build_hash' => 'D7d4p8H',
    'container.build_id' => 'e049f0d8',
    'container.build_time' => 1637826946,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD7d4p8H');
