<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXPkpxUA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXPkpxUA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXPkpxUA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXPkpxUA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXPkpxUA\App_KernelDevDebugContainer([
    'container.build_hash' => 'XPkpxUA',
    'container.build_id' => 'b9ef90a3',
    'container.build_time' => 1639585328,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXPkpxUA');
